runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /images
  static_dir: images

- url: /(.*)\.(html|js|json|css)
  static_files: \1.\2
  upload: (.*)\.(html|js|json|css)

- url: /
  static_files: index.html
  upload: index\.html
  http_headers:
    Link: '</elements/gdgspain-app/gdgspain-app.html>; rel=preload; as=document'

skip_files:
- ^(.*/)?app\.yaml
